site_name: egrader documentation
site_url: https://videojogoslusofona.github.io/egrader
repo_url: https://github.com/VideojogosLusofona/egrader
edit_uri: https://github.com/VideojogosLusofona/egrader/edit/master/docs/docs/
site_description: Documentation for the egrader autograder
site_author: Nuno Fachada
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="CC-BY License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>

theme:
  name: material
  custom_dir: overrides
  logo: img/logo_128x128.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    accent: deep orange
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
          options:
            docstring_style: google
            show_root_toc_entry: false
            show_submodules: no
            heading_level: 2
            line_length: 80
            show_signature_annotations: true
            separate_signature: true

watch:
  - ../egrader

nav:
  - Home: index.md
  - Usage: usage.md
  - Reference: reference.md
  - Development: dev.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 2
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
