name: Coverage

on:
  pull_request:
    branches: [main]
    paths: [ 'egrader/**', 'tests/**', '.github/workflows/cov.yml' ]
  push:
    branches: [main]
    paths: [ 'egrader/**', 'tests/**', '.github/workflows/cov.yml' ]
    tags: '*'
  workflow_dispatch:

jobs:
  determine-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup latest Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install pip --upgrade
        pip install .[dev]
    - name: Test with pytest and create coverage report
      run: pytest --cov=egrader --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
