name: Tests

on:
  pull_request:
    branches: [main]
    paths: [ 'egrader/**', 'tests/**', 'pyproject.toml' ]
  push:
    branches: [main]
    paths: [ 'egrader/**', 'tests/**', 'pyproject.toml' ]
    tags: '*'

jobs:
  run-tests:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['3.10', '3.12']
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Setup latest Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        pip install pip --upgrade
        pip install .[dev]
    - name: Test with pytest
      run: pytest
